---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: 
teacher_info: ''
manual_evaluation: false
choices:
- value: A) Su valor puede ser cualquier número real.
  checked: false
- value: B) Siempre es creciente.
  checked: false
- value: C) Su gráfica es continua para todos los valores del rango.
  checked: false
- value: D) Es continua por tramos.
  checked: true
