---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: A) Su valor puede ser cualquier número real.
  checked: false
- !ruby/hash:BSON::Document
  value: B) Siempre es creciente.
  checked: false
- !ruby/hash:BSON::Document
  value: C) Su gráfica es continua para todos los valores del rango.
  checked: false
- !ruby/hash:BSON::Document
  value: D) Es continua por tramos.
  checked: true
