---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: 
teacher_info: ''
manual_evaluation: false
choices:
- value: La función de probabilidad de una variable aleatoria discreta es un número
    real.
  checked: false
- value: El rango de la función de probabilidad de una variable aleatoria discreta
    es un conjunto numerable.
  checked: true
- value: El dominio de una función de probabilidad es el espacio muestral del respectivo
    experimento aleatorio.
  checked: false
- value: Para una variable aleatoria discreta la función de probabilidad no necesariamente
    representa una probabilidad.
  checked: false
