---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: 
teacher_info: ''
manual_evaluation: false
choices:
- value: A) Dos eventos complementarios, forman una participación de Ω.
  checked: false
- value: B) Dos eventos excluyentes y diferentes del vacío, son independientes.
  checked: false
- value: C) Dos eventos que forman una partición de Ω, son dependientes.
  checked: false
- value: D) Dos eventos excluyentes, diferentes del vacío y dependientes; forman una
    partición de
  checked: true
