---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:BSON::Document
  value: A) En un espacio muestral infinito no numerable con tres dimensiones, la
    probabilidad de un evento definido sobre un plano es cero.
  checked: false
- !ruby/hash:BSON::Document
  value: B) En un espacio muestral infinito todos los puntos son igualmente probables.
  checked: false
- !ruby/hash:BSON::Document
  value: C) Un espacio muestral infinito no numerable siempre tiene un número ilimitado
    de puntos muestrales.
  checked: true
- !ruby/hash:BSON::Document
  value: D) La probabilidad definida sobre un espacio muestral infinito siempre es
    aproximada
  checked: false
